<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-01T16:51:40 IST" name="Suite" finished-at="2025-04-01T16:52:07 IST" duration-ms="27444">
    <groups>
    </groups>
    <test started-at="2025-04-01T16:51:40 IST" name="Test" finished-at="2025-04-01T16:52:07 IST" duration-ms="27444">
      <class name="testCases.TC002_verify_thumbnail_label">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC002_verify_thumbnail_label@4f83df68]" started-at="2025-04-01T16:51:53 IST" name="setup" finished-at="2025-04-01T16:51:58 IST" duration-ms="5555" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_thumbnail_label()[pri:0, instance:testCases.TC002_verify_thumbnail_label@4f83df68]" started-at="2025-04-01T16:51:58 IST" name="verify_thumbnail_label" finished-at="2025-04-01T16:52:07 IST" duration-ms="8988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_thumbnail_label -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCases.TC002_verify_thumbnail_label@4f83df68]" started-at="2025-04-01T16:52:07 IST" name="teardown" finished-at="2025-04-01T16:52:07 IST" duration-ms="338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC002_verify_thumbnail_label -->
      <class name="testCases.TC001_notif_header_check">
        <test-method is-config="true" signature="setup()[pri:0, instance:testCases.TC001_notif_header_check@67c27493]" started-at="2025-04-01T16:51:40 IST" name="setup" finished-at="2025-04-01T16:51:46 IST" duration-ms="5652" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verfiy_notification_header_in_capital()[pri:0, instance:testCases.TC001_notif_header_check@67c27493]" started-at="2025-04-01T16:51:46 IST" name="verfiy_notification_header_in_capital" finished-at="2025-04-01T16:51:52 IST" duration-ms="6429" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NOTIFICATIONS] but found [Notifications]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NOTIFICATIONS] but found [Notifications]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageObject.notificationPage.checkNotiHeader(notificationPage.java:24)
at testCases.TC001_notif_header_check.verfiy_notification_header_in_capital(TC001_notif_header_check.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfiy_notification_header_in_capital -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCases.TC001_notif_header_check@67c27493]" started-at="2025-04-01T16:51:52 IST" name="teardown" finished-at="2025-04-01T16:51:53 IST" duration-ms="454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC001_notif_header_check -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
